name: Code Check
on:
  push:
    branches:
      - develop
      - release
  pull_request: {}

concurrency:
  group: ${{ github.job }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    name: ESLint-TypeScript
    runs-on: ubuntu-latest
    steps:
      - name: ⬇️ Checkout repo
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm ci

      - name: ⎔ Setup node
        uses: actions/setup-node@v3

      - name: 📥 Download deps
        run: npm install --frozen-lockfile

      # - name: 🔬 Lint
      # run: npm run lint

      - name: 🔎 Build check
        run: npm run build

      # - name: 🃏 Run jest
      #   run: npm run test
